# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ccheemeng/miniconda3/envs/3d-wrapping/bin/cmake

# The command to remove a file.
RM = /home/ccheemeng/miniconda3/envs/3d-wrapping/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Chee Meng/Desktop/3d-wrapping"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Chee Meng/Desktop/3d-wrapping"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/ccheemeng/miniconda3/envs/3d-wrapping/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ccheemeng/miniconda3/envs/3d-wrapping/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Chee Meng/Desktop/3d-wrapping/CMakeFiles" "/mnt/c/Users/Chee Meng/Desktop/3d-wrapping//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Chee Meng/Desktop/3d-wrapping/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named building_mesh_wrap

# Build rule for target.
building_mesh_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 building_mesh_wrap
.PHONY : building_mesh_wrap

# fast build rule for target.
building_mesh_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/building_mesh_wrap.dir/build.make CMakeFiles/building_mesh_wrap.dir/build
.PHONY : building_mesh_wrap/fast

#=============================================================================
# Target rules for targets named ALL_CGAL_TARGETS

# Build rule for target.
ALL_CGAL_TARGETS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ALL_CGAL_TARGETS
.PHONY : ALL_CGAL_TARGETS

# fast build rule for target.
ALL_CGAL_TARGETS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ALL_CGAL_TARGETS.dir/build.make CMakeFiles/ALL_CGAL_TARGETS.dir/build
.PHONY : ALL_CGAL_TARGETS/fast

#=============================================================================
# Target rules for targets named cgal_check_build_system

# Build rule for target.
cgal_check_build_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgal_check_build_system
.PHONY : cgal_check_build_system

# fast build rule for target.
cgal_check_build_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgal_check_build_system.dir/build.make CMakeFiles/cgal_check_build_system.dir/build
.PHONY : cgal_check_build_system/fast

#=============================================================================
# Target rules for targets named mixed_inputs_wrap

# Build rule for target.
mixed_inputs_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mixed_inputs_wrap
.PHONY : mixed_inputs_wrap

# fast build rule for target.
mixed_inputs_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mixed_inputs_wrap.dir/build.make CMakeFiles/mixed_inputs_wrap.dir/build
.PHONY : mixed_inputs_wrap/fast

#=============================================================================
# Target rules for targets named pause_and_resume_wrapping

# Build rule for target.
pause_and_resume_wrapping: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pause_and_resume_wrapping
.PHONY : pause_and_resume_wrapping

# fast build rule for target.
pause_and_resume_wrapping/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pause_and_resume_wrapping.dir/build.make CMakeFiles/pause_and_resume_wrapping.dir/build
.PHONY : pause_and_resume_wrapping/fast

#=============================================================================
# Target rules for targets named point_set_wrap

# Build rule for target.
point_set_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 point_set_wrap
.PHONY : point_set_wrap

# fast build rule for target.
point_set_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point_set_wrap.dir/build.make CMakeFiles/point_set_wrap.dir/build
.PHONY : point_set_wrap/fast

#=============================================================================
# Target rules for targets named successive_wraps

# Build rule for target.
successive_wraps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 successive_wraps
.PHONY : successive_wraps

# fast build rule for target.
successive_wraps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/successive_wraps.dir/build.make CMakeFiles/successive_wraps.dir/build
.PHONY : successive_wraps/fast

#=============================================================================
# Target rules for targets named triangle_mesh_wrap

# Build rule for target.
triangle_mesh_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle_mesh_wrap
.PHONY : triangle_mesh_wrap

# fast build rule for target.
triangle_mesh_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_mesh_wrap.dir/build.make CMakeFiles/triangle_mesh_wrap.dir/build
.PHONY : triangle_mesh_wrap/fast

#=============================================================================
# Target rules for targets named triangle_soup_wrap

# Build rule for target.
triangle_soup_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle_soup_wrap
.PHONY : triangle_soup_wrap

# fast build rule for target.
triangle_soup_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_soup_wrap.dir/build.make CMakeFiles/triangle_soup_wrap.dir/build
.PHONY : triangle_soup_wrap/fast

#=============================================================================
# Target rules for targets named volumetric_wrap

# Build rule for target.
volumetric_wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 volumetric_wrap
.PHONY : volumetric_wrap

# fast build rule for target.
volumetric_wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/volumetric_wrap.dir/build.make CMakeFiles/volumetric_wrap.dir/build
.PHONY : volumetric_wrap/fast

#=============================================================================
# Target rules for targets named wrap_from_cavity

# Build rule for target.
wrap_from_cavity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wrap_from_cavity
.PHONY : wrap_from_cavity

# fast build rule for target.
wrap_from_cavity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wrap_from_cavity.dir/build.make CMakeFiles/wrap_from_cavity.dir/build
.PHONY : wrap_from_cavity/fast

building_mesh_wrap.o: building_mesh_wrap.cpp.o
.PHONY : building_mesh_wrap.o

# target to build an object file
building_mesh_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/building_mesh_wrap.dir/build.make CMakeFiles/building_mesh_wrap.dir/building_mesh_wrap.cpp.o
.PHONY : building_mesh_wrap.cpp.o

building_mesh_wrap.i: building_mesh_wrap.cpp.i
.PHONY : building_mesh_wrap.i

# target to preprocess a source file
building_mesh_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/building_mesh_wrap.dir/build.make CMakeFiles/building_mesh_wrap.dir/building_mesh_wrap.cpp.i
.PHONY : building_mesh_wrap.cpp.i

building_mesh_wrap.s: building_mesh_wrap.cpp.s
.PHONY : building_mesh_wrap.s

# target to generate assembly for a file
building_mesh_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/building_mesh_wrap.dir/build.make CMakeFiles/building_mesh_wrap.dir/building_mesh_wrap.cpp.s
.PHONY : building_mesh_wrap.cpp.s

mixed_inputs_wrap.o: mixed_inputs_wrap.cpp.o
.PHONY : mixed_inputs_wrap.o

# target to build an object file
mixed_inputs_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mixed_inputs_wrap.dir/build.make CMakeFiles/mixed_inputs_wrap.dir/mixed_inputs_wrap.cpp.o
.PHONY : mixed_inputs_wrap.cpp.o

mixed_inputs_wrap.i: mixed_inputs_wrap.cpp.i
.PHONY : mixed_inputs_wrap.i

# target to preprocess a source file
mixed_inputs_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mixed_inputs_wrap.dir/build.make CMakeFiles/mixed_inputs_wrap.dir/mixed_inputs_wrap.cpp.i
.PHONY : mixed_inputs_wrap.cpp.i

mixed_inputs_wrap.s: mixed_inputs_wrap.cpp.s
.PHONY : mixed_inputs_wrap.s

# target to generate assembly for a file
mixed_inputs_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mixed_inputs_wrap.dir/build.make CMakeFiles/mixed_inputs_wrap.dir/mixed_inputs_wrap.cpp.s
.PHONY : mixed_inputs_wrap.cpp.s

pause_and_resume_wrapping.o: pause_and_resume_wrapping.cpp.o
.PHONY : pause_and_resume_wrapping.o

# target to build an object file
pause_and_resume_wrapping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pause_and_resume_wrapping.dir/build.make CMakeFiles/pause_and_resume_wrapping.dir/pause_and_resume_wrapping.cpp.o
.PHONY : pause_and_resume_wrapping.cpp.o

pause_and_resume_wrapping.i: pause_and_resume_wrapping.cpp.i
.PHONY : pause_and_resume_wrapping.i

# target to preprocess a source file
pause_and_resume_wrapping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pause_and_resume_wrapping.dir/build.make CMakeFiles/pause_and_resume_wrapping.dir/pause_and_resume_wrapping.cpp.i
.PHONY : pause_and_resume_wrapping.cpp.i

pause_and_resume_wrapping.s: pause_and_resume_wrapping.cpp.s
.PHONY : pause_and_resume_wrapping.s

# target to generate assembly for a file
pause_and_resume_wrapping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pause_and_resume_wrapping.dir/build.make CMakeFiles/pause_and_resume_wrapping.dir/pause_and_resume_wrapping.cpp.s
.PHONY : pause_and_resume_wrapping.cpp.s

point_set_wrap.o: point_set_wrap.cpp.o
.PHONY : point_set_wrap.o

# target to build an object file
point_set_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point_set_wrap.dir/build.make CMakeFiles/point_set_wrap.dir/point_set_wrap.cpp.o
.PHONY : point_set_wrap.cpp.o

point_set_wrap.i: point_set_wrap.cpp.i
.PHONY : point_set_wrap.i

# target to preprocess a source file
point_set_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point_set_wrap.dir/build.make CMakeFiles/point_set_wrap.dir/point_set_wrap.cpp.i
.PHONY : point_set_wrap.cpp.i

point_set_wrap.s: point_set_wrap.cpp.s
.PHONY : point_set_wrap.s

# target to generate assembly for a file
point_set_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point_set_wrap.dir/build.make CMakeFiles/point_set_wrap.dir/point_set_wrap.cpp.s
.PHONY : point_set_wrap.cpp.s

successive_wraps.o: successive_wraps.cpp.o
.PHONY : successive_wraps.o

# target to build an object file
successive_wraps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/successive_wraps.dir/build.make CMakeFiles/successive_wraps.dir/successive_wraps.cpp.o
.PHONY : successive_wraps.cpp.o

successive_wraps.i: successive_wraps.cpp.i
.PHONY : successive_wraps.i

# target to preprocess a source file
successive_wraps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/successive_wraps.dir/build.make CMakeFiles/successive_wraps.dir/successive_wraps.cpp.i
.PHONY : successive_wraps.cpp.i

successive_wraps.s: successive_wraps.cpp.s
.PHONY : successive_wraps.s

# target to generate assembly for a file
successive_wraps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/successive_wraps.dir/build.make CMakeFiles/successive_wraps.dir/successive_wraps.cpp.s
.PHONY : successive_wraps.cpp.s

triangle_mesh_wrap.o: triangle_mesh_wrap.cpp.o
.PHONY : triangle_mesh_wrap.o

# target to build an object file
triangle_mesh_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_mesh_wrap.dir/build.make CMakeFiles/triangle_mesh_wrap.dir/triangle_mesh_wrap.cpp.o
.PHONY : triangle_mesh_wrap.cpp.o

triangle_mesh_wrap.i: triangle_mesh_wrap.cpp.i
.PHONY : triangle_mesh_wrap.i

# target to preprocess a source file
triangle_mesh_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_mesh_wrap.dir/build.make CMakeFiles/triangle_mesh_wrap.dir/triangle_mesh_wrap.cpp.i
.PHONY : triangle_mesh_wrap.cpp.i

triangle_mesh_wrap.s: triangle_mesh_wrap.cpp.s
.PHONY : triangle_mesh_wrap.s

# target to generate assembly for a file
triangle_mesh_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_mesh_wrap.dir/build.make CMakeFiles/triangle_mesh_wrap.dir/triangle_mesh_wrap.cpp.s
.PHONY : triangle_mesh_wrap.cpp.s

triangle_soup_wrap.o: triangle_soup_wrap.cpp.o
.PHONY : triangle_soup_wrap.o

# target to build an object file
triangle_soup_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_soup_wrap.dir/build.make CMakeFiles/triangle_soup_wrap.dir/triangle_soup_wrap.cpp.o
.PHONY : triangle_soup_wrap.cpp.o

triangle_soup_wrap.i: triangle_soup_wrap.cpp.i
.PHONY : triangle_soup_wrap.i

# target to preprocess a source file
triangle_soup_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_soup_wrap.dir/build.make CMakeFiles/triangle_soup_wrap.dir/triangle_soup_wrap.cpp.i
.PHONY : triangle_soup_wrap.cpp.i

triangle_soup_wrap.s: triangle_soup_wrap.cpp.s
.PHONY : triangle_soup_wrap.s

# target to generate assembly for a file
triangle_soup_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangle_soup_wrap.dir/build.make CMakeFiles/triangle_soup_wrap.dir/triangle_soup_wrap.cpp.s
.PHONY : triangle_soup_wrap.cpp.s

volumetric_wrap.o: volumetric_wrap.cpp.o
.PHONY : volumetric_wrap.o

# target to build an object file
volumetric_wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/volumetric_wrap.dir/build.make CMakeFiles/volumetric_wrap.dir/volumetric_wrap.cpp.o
.PHONY : volumetric_wrap.cpp.o

volumetric_wrap.i: volumetric_wrap.cpp.i
.PHONY : volumetric_wrap.i

# target to preprocess a source file
volumetric_wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/volumetric_wrap.dir/build.make CMakeFiles/volumetric_wrap.dir/volumetric_wrap.cpp.i
.PHONY : volumetric_wrap.cpp.i

volumetric_wrap.s: volumetric_wrap.cpp.s
.PHONY : volumetric_wrap.s

# target to generate assembly for a file
volumetric_wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/volumetric_wrap.dir/build.make CMakeFiles/volumetric_wrap.dir/volumetric_wrap.cpp.s
.PHONY : volumetric_wrap.cpp.s

wrap_from_cavity.o: wrap_from_cavity.cpp.o
.PHONY : wrap_from_cavity.o

# target to build an object file
wrap_from_cavity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wrap_from_cavity.dir/build.make CMakeFiles/wrap_from_cavity.dir/wrap_from_cavity.cpp.o
.PHONY : wrap_from_cavity.cpp.o

wrap_from_cavity.i: wrap_from_cavity.cpp.i
.PHONY : wrap_from_cavity.i

# target to preprocess a source file
wrap_from_cavity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wrap_from_cavity.dir/build.make CMakeFiles/wrap_from_cavity.dir/wrap_from_cavity.cpp.i
.PHONY : wrap_from_cavity.cpp.i

wrap_from_cavity.s: wrap_from_cavity.cpp.s
.PHONY : wrap_from_cavity.s

# target to generate assembly for a file
wrap_from_cavity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wrap_from_cavity.dir/build.make CMakeFiles/wrap_from_cavity.dir/wrap_from_cavity.cpp.s
.PHONY : wrap_from_cavity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ALL_CGAL_TARGETS"
	@echo "... cgal_check_build_system"
	@echo "... building_mesh_wrap"
	@echo "... mixed_inputs_wrap"
	@echo "... pause_and_resume_wrapping"
	@echo "... point_set_wrap"
	@echo "... successive_wraps"
	@echo "... triangle_mesh_wrap"
	@echo "... triangle_soup_wrap"
	@echo "... volumetric_wrap"
	@echo "... wrap_from_cavity"
	@echo "... building_mesh_wrap.o"
	@echo "... building_mesh_wrap.i"
	@echo "... building_mesh_wrap.s"
	@echo "... mixed_inputs_wrap.o"
	@echo "... mixed_inputs_wrap.i"
	@echo "... mixed_inputs_wrap.s"
	@echo "... pause_and_resume_wrapping.o"
	@echo "... pause_and_resume_wrapping.i"
	@echo "... pause_and_resume_wrapping.s"
	@echo "... point_set_wrap.o"
	@echo "... point_set_wrap.i"
	@echo "... point_set_wrap.s"
	@echo "... successive_wraps.o"
	@echo "... successive_wraps.i"
	@echo "... successive_wraps.s"
	@echo "... triangle_mesh_wrap.o"
	@echo "... triangle_mesh_wrap.i"
	@echo "... triangle_mesh_wrap.s"
	@echo "... triangle_soup_wrap.o"
	@echo "... triangle_soup_wrap.i"
	@echo "... triangle_soup_wrap.s"
	@echo "... volumetric_wrap.o"
	@echo "... volumetric_wrap.i"
	@echo "... volumetric_wrap.s"
	@echo "... wrap_from_cavity.o"
	@echo "... wrap_from_cavity.i"
	@echo "... wrap_from_cavity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

